/**
* @author Amanjot Kaur
* @date 
* @description : Landing Page Wrapper.
Modification Log:
------------------------------------------------------------------------------------
Developer Mod Number Date Description
------------------------------------------------------------------------------------
*/
public class Lightning_LandingPageResponseWrapper{ 
    public DataTableResponse lstDataTableRecs; 
    public Lightning_LandingPageResponseWrapper(){
    }   
}